#!/bin/bash

echo "🔍 Firefox Developer Edition - Konfigurationsprüfung"
echo ""
echo "Bitte führen Sie folgende Schritte in Firefox Developer Edition aus:"
echo ""
echo "1. Öffnen Sie: about:config"
echo "2. Suchen Sie nach: xpinstall.signatures.required"
echo "3. Der Wert sollte sein: false"
echo ""
echo "Falls der Wert 'true' ist:"
echo "   → Doppelklicken Sie darauf um auf 'false' zu setzen"
echo ""
echo "4. Öffnen Sie: about:debugging#/runtime/this-firefox"
echo "5. Prüfen Sie ob 'Revolution Web Connector' dort aufgelistet ist"
echo ""
echo "Falls das Addon NICHT dort ist:"
echo "   → Klicken Sie 'Temporäres Add-on laden...'"
echo "   → Wählen Sie: $PWD/manifest.json"
echo ""
echo "6. WICHTIG: Prüfen Sie, ob Sie wirklich Firefox Developer Edition nutzen"
echo "   → Öffnen Sie: about:support"
echo "   → Suchen Sie 'Name': Sollte 'Firefox Developer Edition' sein"
echo ""
echo "Falls dort 'Firefox' (ohne Developer Edition) steht:"
echo "   → Sie nutzen den falschen Browser!"
echo "   → Firefox Developer Edition Icon ist orange/blau, nicht nur blau"
echo ""
